"""empty message

Revision ID: f064c2218f
Revises: None
Create Date: 2015-09-28 09:39:37.968305

"""

# revision identifiers, used by Alembic.
revision = 'f064c2218f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
